package cn.zhengzhaoyu.resume.common.model;

import cn.zhengzhaoyu.resume.common.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	
}
