package cn.zhengzhaoyu.resume.common.model;

import cn.zhengzhaoyu.resume.common.model.base.BaseProjectInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectInfo extends BaseProjectInfo<ProjectInfo> {
	
}
