package cn.zhengzhaoyu.resume.common.model;

import cn.zhengzhaoyu.resume.common.model.base.BaseTechStack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TechStack extends BaseTechStack<TechStack> {
	
}
