package cn.zhengzhaoyu.resume.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPname(java.lang.String pname) {
		set("pname", pname);
		return (M)this;
	}

	public java.lang.String getPname() {
		return get("pname");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
		return (M)this;
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public M setTimeStart(java.util.Date timeStart) {
		set("time_start", timeStart);
		return (M)this;
	}

	public java.util.Date getTimeStart() {
		return get("time_start");
	}

	public M setTimeFinish(java.util.Date timeFinish) {
		set("time_finish", timeFinish);
		return (M)this;
	}

	public java.util.Date getTimeFinish() {
		return get("time_finish");
	}

	public M setGithubUrl(java.lang.String githubUrl) {
		set("github_url", githubUrl);
		return (M)this;
	}

	public java.lang.String getGithubUrl() {
		return get("github_url");
	}

}
